export const DISHES = [{
        id: 0,
        name: "Uthappizza",
        image: "/assets/images/uthappizza.png",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
    },
    {
        id: 1,
        name: "Zucchipakoda",
        image: "/assets/images/zucchipakoda.png",
        category: "appetizer",
        label: "",
        price: "1.99",
        featured: false,
        description: "Deep fried Zucchini coated with mildly spiced Chickpea flour batter accompanied with a sweet-tangy tamarind sauce",
    },
    {
        id: 2,
        name: "Vadonut",
        image: "/assets/images/vadonut.png",
        category: "appetizer",
        label: "New",
        price: "1.99",
        featured: false,
        description: "A quintessential ConFusion experience, is it a vada or is it a donut?",
    },
    {
        id: 3,
        name: "ElaiCheese Cake",
        image: "/assets/images/elaicheesecake.png",
        category: "dessert",
        label: "",
        price: "2.99",
        featured: false,
        description: "A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms",
    },
    {
        id: 4,
        name: "Avocado and Egg Toast",
        image: "/assets/images/Avocado and Egg Toast.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
    {
        id: 5,
        name: "Meal with salman and zucchini",
        image: "/assets/images/Meal with salmon and zucchini.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
    {
        id: 6,
        name: "Paella",
        image: "/assets/images/Paella.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
    {
        id: 7,
        name: "Nachos with 3 Deep Sauce",
        image: "/assets/images/Nachos with 3 Deep Sauce.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },

    {
        id: 8,
        name: "Vegan salad bowl",
        image: "/assets/images/Vegan salad bowl.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
    {
        id: 9,
        name: "Spaghetti with meatballs",
        image: "/assets/images/Spaghetti with meatballs.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
    {
        id: 10,
        name: "Stuffed eggplants with youghurt and salad",
        image: "/assets/images/Stuffed eggplants with youghurt and salad.jpg",
        category: "mains",
        label: "Hot",
        price: "4.99",
        featured: true,
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups",
    },
];